### ISSUE TITLE
Panic in syntex-syntax on ctest 0.1.5

### ISSUE THREAD

**Issue by sfackler** [alexcrichton/ctest#21]
Not sure if this is an issue with syntex-syntax or with how ctest is invoking it, but I'm seeing panics: https://circleci.com/gh/sfackler/rust-openssl/1437. Seems like it's something in https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/ossl10x.rs but I haven't narrowed it down beyond that.

**Comment by alexcrichton** [comment]
Ok confirmed fixed both git2 and openssl with https://github.com/alexcrichton/ctest/commit/4d509e6c1d618c726a30a9cb5a5df5bdbfbfe70a, so closing.

**Comment by alexcrichton** [comment]
(also published 0.1.6)
