### ISSUE TITLE
Building with `-Werror` breaks certain libraries

### ISSUE THREAD

**Issue by GabrielMajeri** [alexcrichton/ctest#24]
This [source line](https://github.com/alexcrichton/ctest/blob/06e41ac5f8f5f83dda57a106cfc1e801bd7e2f36/src/lib.rs#L583) enables `-Werror` when building. This breaks the [`libz-sys`](https://github.com/alexcrichton/libz-sys) crate's build process.

Is there any reason for enabling `-Werror`? Should it be made optional? Fixing the original C `libz` is another possibility, although that is a harder path.

**Comment by alexcrichton** [comment]
This is unfortunate :(

Right now this library relies on `-Werror` to work at all (otherwise the C compiler just emits warnings for everything we want to be an error). Maybe a more targeted `-wno-foo-bar` can be used here instead?

**Comment by GabrielMajeri** [comment]
Found the actual issue, `ctest` didn't give a false positive, this was an actual bug. Closing for alexcrichton/libz-sys#32.
