### ISSUE TITLE
the cfg example is unclear

### ISSUE THREAD

**Issue by gnzlbg** [alexcrichton/ctest#33]
The example body states: https://docs.rs/ctest/0.1.7/ctest/struct.TestGenerator.html#method.cfg

> The k argument is the #[cfg] value to define, and v is an optional value for differentiating between #[cfg(foo)] and #[cfg(foo = "bar")].

No idea what this exactly means (the example below uses different names). I suppose if I write `k = "foo"` and `v = None` then I get `#[cfg(foo)]`, and if I write `k = "foo"` and `v = Some("bar")` I get `#[cfg(foo = "bar")]`.

Is this correct? 

The following example is shown:

```rust
let mut cfg = TestGenerator::new();
cfg.cfg("foo", None)
   .cfg("bar", Some("baz"));
```

but I have no idea what it is trying to tell me. Maybe add some comments next to each line, stating what the consequences of each `.cfg` invocations are?

**Comment by alexcrichton** [comment]
Your interpretation is correct! Agreed the docs could be more clear :)

The example there is generating `#[cfg(foo)]` and `#[cfg(bar = "baz")]`
