### ISSUE TITLE
static function pointers are broken

### ISSUE THREAD

**Issue by gnzlbg** [alexcrichton/ctest#38]
Examples:

```rust
extern "C" {
#[no_mangle]
pub static mut bar:
extern fn (a: *mut u8, b: *const u16);
}
```

errors on MacOS with

```
error: expected function body after function declarator
cargo:warning=            extern fn(u8, u16) -> ()* __test_static_bar(void) {
```

The problem seems to be that the following invalid C code is generated for these:

```c
extern fn(u8, u16) -> ()* __test_static_bar(void) {
    return &bar;
}
```

That is, it appears that the Rust function type `extern fn(u8, u16) -> ()` is not being translated to the C function type;

**Comment by alexcrichton** [comment]
Looks bad! I think it can largely be fixed [around here](https://github.com/alexcrichton/ctest/blob/52394e1f48270ec38b9d03694ae3276ce4720941/src/lib.rs#L1520-L1523) and transitive functinos.

**Comment by gnzlbg** [comment]
So I have partially fixed this, but I am having a bit of trouble generating the functions that return function pointer types (I have to generate a typedef for the pointer first).

**Comment by alexcrichton** [comment]
The syntax for doing so, while obscure, [is possible to do without a typedef](https://stackoverflow.com/questions/20617067/returning-function-pointer-type)!

**Comment by gnzlbg** [comment]
@alexcrichton yeah, it can be done, but it gets nastier as the function pointers being returned also return function pointers (e.g. `fn() -> fn() -> fn() -> fn()`). I'll try to special case the C code generated for statics to, instead of adding a function that returns a type, have it use that function pointer syntax when the return type is a function pointer.

**Comment by gnzlbg** [comment]
Will be closed by https://github.com/alexcrichton/ctest/pull/39 .
