### ISSUE TITLE
README says documentation has example, it doesn't

### ISSUE THREAD

**Issue by posborne** [alexcrichton/ctest#5]
Just trying to figure out what ctest does and does not do and if it might be something I could integrate into a few projects to help test FFI.  The documentation is quite sparse at the moment.

**Comment by alexcrichton** [comment]
Oh oops! Looks like I forgot to take care of this...

Ok, just filled out the README and a bunch of API docs, hope that helps!

**Comment by posborne** [comment]
Excellent! Thanks!
